### ISSUE TITLE
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

### ISSUE THREAD

**Issue by fanwgwg** [exyte/PopupView#189] opened 2024-05-08 11:32 UTC
Seeing this warning when keyboard shows up with the PopupView, e.g., when the popup contains a TextField.

`Publishing changes from within view updates is not allowed, this will cause undefined behavior.`

![screenshot-20240508-193100](https://github.com/exyte/PopupView/assets/14089267/5f6565d4-b546-4acc-a252-f5e5faf361b9)

**Comment by f3dm76** [comment] 2024-06-17 10:45
Hey @fanwgwg, I placed a TextField inside a popup, and I don't see any issues. Please attach a minimal compilable example and make sure the issue reproduces on this minimal example. Have a nice day

**Comment by iosdevparty** [comment] 2024-07-15 12:02
Hello! I placed a TextField inside a popup and had got problem with "Publishing changes from within view updates is not allowed, this will cause undefined behavior." I have TextField inside GroupsMakingView. 
<img width="1111" alt="Screenshot 2024-07-15 at 15 02 21" src="https://github.com/user-attachments/assets/3fa46f24-b662-46c0-aa4a-5d5e54ec0bd9">


`
        .popup(isPresented: $showGroupMaking) {
            GroupsMakingView(onCreateGroupAction: createGroup)
        } customize: { params in
            params
                .type(.floater(verticalPadding: 40, horizontalPadding: 0, useSafeAreaInset: true))
                .position(.top)
                .appearFrom(.centerScale)
                .closeOnTapOutside(true)
                .closeOnTap(false)
        }
        
`

**Comment by t9mike** [comment] 2024-07-24 11:57
Suggest you attach ZIP of a small Xcode project @iosdevparty that reproduce the issue. That is what the maintainer has requested.

**Comment by f3dm76** [comment] 2024-07-25 04:50
Hey @iosdevparty, I need the code to reproduce - not a picture of code. Please attach a full minimal example, it can be just a text message with code, but a zip is even better. Also please specify xcode, ios and lib versions

**Comment by iosdevparty** [comment] 2024-07-30 13:30
> Hey @iosdevparty, I need the code to reproduce - not a picture of code. Please attach a full minimal example, it can be just a text message with code, but a zip is even better. Also please specify xcode, ios and lib versions

Hello @f3dm76 @t9mike . My xcode Version 15.2 (15C500b).
lib version 3.0.4.
iOS 17.2 iphone15Pro.
And I created simple project from main project. 
[PopupViewBugReport.zip](https://github.com/user-attachments/files/16428728/PopupViewBugReport.zip)

**Comment by muratozturk5** [comment] 2024-10-04 14:58
I have faced same issue, my popup is doesn't contain any TextField.
I tried to add  DispatchQueue.main.async  for two this code
self.keyboardHeight = 0
self.keyboardDisplayed = false

and it looks like it solved the issue. 

Lib Version : 3.0.0
XCode : Version 16.0 (16A242d)
Iphone 16 Pro : IOS 18.0

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/b417e109-2890-411d-92ee-9861518591c8">

**Comment by f3dm76** [comment] 2024-10-14 04:38
Hey @muratozturk5, this warning should have been fixed in 3.1.2, please check it out. Have a great day!

Hey @iosdevparty, thank you for the example, but I still don't see the warning. Please update to latest popup and xcode versions. If you are still seeing the issue, please consider commiting a PR fixing it - it should be something easily fixes with DispatchQueue.main.async and/or @MainActor. Have a good day!

**Comment by muratozturk5** [comment] 2024-10-18 23:51
> Hey @muratozturk5, this warning should have been fixed in 3.1.2, please check it out. Have a great day!

Hey @f3dm76, DispatchQueue.main.async is solved the issue in 3.1.2, Thank you.
I think you can close the issue now

**Closed** 2024-10-19 07:40 UTC
