### ISSUE TITLE
Unable to show toast when tab bar is visible

### ISSUE THREAD

**Issue by juandahurt** [exyte/PopupView#74] opened 2022-08-25 16:39 UTC
I've been trying to show a toast in my custom View (which I'm wrapping in a UIViewController and then in a UITabBarController). When the tab bar is hidden it works just fine, but when the tab bar is shown  it hovers the toast (I suppose) so it never appears. I want the toast to appear above the tab bar, Is there any way to achieve this? O am I just using it the wrong way?

| Tab Bar Hidden | Tab Bar Visible |
| --- | --- |
|  ![Simulator Screen Shot - iPhone 11 - 2022-08-25 at 11 36 48](https://user-images.githubusercontent.com/26754335/186721687-77c8428e-099c-47a2-a03d-34f19908bb42.png) | ![Simulator Screen Shot - iPhone 11 - 2022-08-25 at 11 36 22](https://user-images.githubusercontent.com/26754335/186721699-6a68e11a-9c4d-455f-badf-194d660978aa.png) |

**Comment by juandahurt** [comment] 2022-08-25 18:05
Found a workaround. It looks like if you apply and offset (it can be 1, for example) to the view, it works just fine. Not sure why but it works.

![Simulator Screen Shot - iPhone 11 - 2022-08-25 at 13 03 08](https://user-images.githubusercontent.com/26754335/186737499-74cc955e-4ecb-448e-a57e-5036e805722b.png)

**Comment by f3dm76** [comment] 2022-09-15 06:15
Hey @juandahurt, could you please attach a minimal reproducible code sample? I need to see if you are changing the main view's height when showing tabbar, how you are wrapping it all in UIViewController and what is your safe area situation. Popup view counts its position depending on the height of a view it is attached to, so it could be that you need to attach it to content of your tab control, not the whole controller. It indeed hides behind navbars and probably also tabbars since currently Apple doesn't give devs the right to display anything above them. Adding any offset could be changing safe area policy, and that is why it fixes itself. But I cannot say any of that for sure unless I see a reproducible piece of code.

**Comment by f3dm76** [comment] 2022-09-26 04:45
I'm closing this one for now, please feel free to reopen if you are still having this issue

**Closed by f3dm76** 2022-09-26 04:45 UTC
