### ISSUE TITLE
Popup dismiss and slide to close broken on with 2.6.2

### ISSUE THREAD

**Issue by edan291** [exyte/PopupView#144] opened 2023-09-07 00:34 UTC
Just a heads up.. this seems to have broken since 2.6.2. Some obscure message about an 'onChange' handler in the console. no useful information other than that. Dismiss callback wont even output a print statement.

Initially noticed on IOS 17 Beta (Sim and Device) , but i've since tested in IOS 15.4 sim and it wasn't working there either. Oddly, it works on my iPad OS 17. ???

Was banging my head against the wall on this all day then saw you'd put out a couple of releases. Rolled back to 2.6.1 and all good again. 

lmk if I can be of any more help. Thanks for the package! One of the best popup modules I've found. Bridges a gap before presentationDetents can be widely adopted.

**Comment by edan291** [comment] 2023-09-07 00:58
(The message said something about firing multiple onChange handlers)

**Comment by f3dm76** [comment] 2023-09-07 07:19
Hey @edan291, thank you for your kind words. I tested your issue, but couldn't reproduce. lib version 2.6.3, both ios 17.0 and 15.0 iPhone sim (I don't know how to download IOS 15.4 sim, xcode only offers 15.0), both xcode 15 beta 7 and xcode 14.3.1: dragToDismiss works and callback gets called with correct dismiss source. Here is my code:

```
struct ContentView: View {

    @State var isPresented1 = false

    var body: some View {
        VStack {
            Button("First") {
                isPresented1 = true
            }
        }
        .popup(isPresented: $isPresented1) {
                Color.black.frame(width: 100, height: 100)
        } customize: {
            $0
                .type(.floater(verticalPadding: 0, useSafeAreaInset: false))
                .position(.bottomLeading)
                .closeOnTap(false)
                .dragToDismiss(true)
                .dismissSourceCallback { source in
                    print(source)
                }
        }
}
```
Could you please provide your xcode version, and a full minimal compilable example, and please make sure the issue reproduces on this minimal example. Have a nice day

**Comment by marcozabo** [comment] 2023-09-19 13:02
Same problem here

How to reproduce: just use the PopupExample app, add a new button to PopupMiddle below the existing one

           //Added button
            Button("No Thanks") {
                onClose()
            }
            .buttonStyle(.plain)
            .font(.system(size: 18, weight: .bold))
            .frame(maxWidth: .infinity)
            .padding(.vertical, 18)
            .padding(.horizontal, 24)
            .foregroundColor(.white)
            .background(Color(hex: "9265F8"))
            .cornerRadius(12)



then run on Xcode 14.3 and iOS 16.4 simulator, both buttons in the modifyed PopupMiddle wont dismiss 

[PopupView-modified.zip](https://github.com/exyte/PopupView/files/12660469/PopupView-modified.zip)

**Comment by Holychris56** [comment] 2023-09-21 15:59
same issue here

**Comment by f3dm76** [comment] 2023-09-23 07:33
Hey guys, sorry for the delay, please check out version 2.7.0, issue should be fixed there. Have a great day!

**Closed** 2023-09-23 07:36 UTC
