### ISSUE TITLE
Action/Input Sheet Not Fully Dismissing

### ISSUE THREAD

**Issue by matthewjamesr** [exyte/PopupView#169] opened 2024-01-17 05:33 UTC
Hello,

I have implemented an action sheet visually dismisses, however, the invisible layer seems to remain active, rendering the UI unresponsive. Below is the relevant code.

```
ForEach(goals["daily"]!, id: \.id) { goal in
                        
                        VStack {
                            
                            HStack {
                                if (goal.id > 0) {
                                    Text(goal.type)
                                        .font(.system(size: 14, weight: .medium))
                                        .padding(.bottom, -5)
                                        .padding(.top)
                                } else {
                                    Text(goal.type)
                                        .font(.system(size: 14, weight: .medium))
                                        .padding(.bottom, -5)
                                }
                                
                                Spacer()
                                
                                if (goal.id > 0) {
                                    Text(String(goal.amount))
                                        .font(.system(size: 14, weight: .light))
                                        .padding(.top)
                                } else {
                                    Text(String(goal.amount))
                                        .font(.system(size: 14, weight: .light))
                                }
                            }
                            .padding(.bottom, 5)
                            
                            //Replace with loop of Goal types
                            
                            if goal.type == "Steps" {
                                ProgressView(value: Double(currentMetrics.steps), total: Double(goal.amount))
                                    .background(.black)
                                    .tint(currentMetrics.steps > goal.amount ? .cyan : .green)
                                    .cornerRadius(10)
                            } else if goal.type == "Active Minutes" {
                                ProgressView(value: Double(currentMetrics.activeMinutes), total: Double(goal.amount))
                                    .background(.black)
                                    .tint(currentMetrics.activeMinutes > goal.amount ? .cyan : .green)
                                    .cornerRadius(10)
                            } else if goal.type == "VO2 Max" {
                                ProgressView(value: Double(currentMetrics.vo2Max), total: Double(goal.amount))
                                    .background(.black)
                                    .tint(.green)
                                    .cornerRadius(10)
                            }
                            
                        }
                        .popup(isPresented: $showingPopup) {
                            //GoalPopup(goal: .constant(goal))
                            
                            VStack(spacing: 0) {
                                Text("Nickname")
                                    .foregroundColor(.black)
                                    .font(.system(size: 20, weight: .bold))
                                    .kerning(0.38)
                                
                                TextField("Nickname", text: .constant("dd"))
                                    .padding()
                                    .frame(height: 44)
                                    .background {
                                        RoundedRectangle(cornerRadius: 12)
                                            .stroke(Color(red: 1, green: 0.23, blue: 0.19), lineWidth: 0.5)
                                    }
                                    .padding(.top, 6)
                                
                                Button {
                                    showingPopup = false
                                } label: {
                                    Text("Save changes")
                                        .buttonStyle(.plain)
                                        .font(.system(size: 17))
                                        .frame(maxWidth: .infinity)
                                        .frame(height: 44)
                                        .background {
                                            RoundedRectangle(cornerRadius: 12)
                                                .fill(Color(red: 0.29, green: 0.38, blue: 1))
                                        }
                                }
                                .buttonStyle(.plain)
                                .foregroundColor(.white)
                                .padding(.top, 12)
                            }
                            .padding(16)
                            .background(Color.white.cornerRadius(18))
                            .padding(.horizontal, 8)
                            .padding(.bottom, 30)
                            
                        } customize: {
                            $0
                                .type(.toast)
                                .position(.bottom)
                                .closeOnTap(false)
                                .dragToDismiss(true)
                                .isOpaque(true)
                                .dismissCallback({
                                    showingPopup = false
                                })
                        }
                        .onTapGesture {
                            showingPopup = true
                        }
                    }
                    ```

**Comment by f3dm76** [comment] 2024-01-17 05:45
Hey @matthewjamesr, this code is not compilable, please provide an isolated piece of code I can launch to fix the problem. Also please specify platform, ios and xcode versions. Have a nice day

**Comment by GaneshManickam** [comment] 2024-03-15 12:30
@f3dm76 
Even i'm facing the same issue. It can be easily reproducible when hide and show multiple popup back and forth. even able to reproducible on simulator.

**Comment by f3dm76** [comment] 2024-05-06 10:18
@GaneshManickam, if you are getting this error ("Currently, only presenting a single sheet is supported."), then you are most likely using opaque popups, which are SwiftUIs fullscreen sheets under the hood - and only one of those can be displayed at a time. So you shouldn't be doing this with opaque popups. Anyway, I am not able to reproduce the issue with any kind of popups. Please provide a compilable minimal working example of the issue, so I can help you.

**Comment by f3dm76** [comment] 2024-06-18 08:11
It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue. Please be sure to attach minimal compilable reproducible example. Have a nice day!

**Closed by f3dm76** 2024-06-18 08:11 UTC
