### ISSUE TITLE
App crash SIGABRT  , caused by the GeometryReader in the FrameGetter and SafeAreaGetter of the Util class

### ISSUE THREAD

**Issue by kobeisgod** [exyte/PopupView#184] opened 2024-04-08 14:02 UTC
After opening the App from the widget, it's likely for the App to crash.Error message as follows:

`$s14ExytePopupView11FrameGetterV4body7contentQr7SwiftUI01_C16Modifier_ContentVyACG_tFAF03AnyC0VAF13GeometryProxyVcfU_yyScMYccfU_ + 140`

`$s14ExytePopupView14SafeAreaGetterV4body7contentQr7SwiftUI01_C16Modifier_ContentVyACG_tFAF03AnyC0VAF13GeometryProxyVcfU_yyScMYccfU_ + 40`

The crash is likely caused by the GeometryReader in the FrameGetter and SafeAreaGetter of the Util class. Could you please take a look at how to fix this bug?

![1](https://github.com/exyte/PopupView/assets/7081228/be9a8492-c878-4f89-b869-46b3a1b2e471)
![2](https://github.com/exyte/PopupView/assets/7081228/336aa30c-9e8d-4fd5-9c06-058c5e90e05d)

**Comment by bunsberry** [comment] 2024-04-14 10:58
It seems in some cases the code of FrameGetter or/and SafeAreaGetter cause an infite loop. Facing the same issue

**Comment by bunsberry** [comment] 2024-04-14 11:30
I had the same crush - so I used swiftui instrument to check the body getters. There were severe hangs because of popup view and another problem of mine. It seems the problem is not the exyte popupview itself but the code that keeps calling the popup. And it could be you just ran out of memory and system terminated the app at another popup go. When I fixed my issue the SIGABRT went away. Maybe it's the same for you

**Comment by kobeisgod** [comment] 2024-04-17 02:08
@bunsberry  
I greatly appreciate your suggestions. I'm going to check my code again and see if I can fix this issue.

**Comment by f3dm76** [comment] 2024-05-06 08:42
Hey @kobeisgod, did you manage to locate what causes the problem? This `FrameGetter` is a standard frame getting practice in SwiftUI, as far as I know, and shouldn't cause any issues by itself. If you think exyte popup causes this issue, please attach a minimal example so I can reproduce the crash

**Comment by f3dm76** [comment] 2024-06-18 08:11
It's been a while, so I'll close this one for now. Please feel free to reopen if you are still having the issue. Please be sure to attach minimal compilable reproducible example. Have a nice day!

**Closed by f3dm76** 2024-06-18 08:11 UTC
